######################################################################
# Automatically generated by qmake (3.0) Sun Mar 16 21:53:11 2014
######################################################################

QT += widgets
TEMPLATE = app
TARGET = game_of_life
INCLUDEPATH += .

# Input
HEADERS += golBoard.h golWindow.h
SOURCES += golBoard.cpp golWindow.cpp main.cpp
